<?php
/**
 * Created by PhpStorm.
 * User: foreverzjz
 * Date: 2018/9/5
 * Time: 下午4:11
 */

namespace App\Utility;

use EasySwoole\Config;
use EasySwoole\Core\Component\Pool\AbstractInterface\Pool;
use EasySwoole\Core\Component\Trigger;
use EasySwoole\Core\Swoole\Coroutine\Client\Mysql;

class MysqlPool extends Pool
{
    function getObj($timeOut = 0.1):?Mysql
    {
        return parent::getObj($timeOut); // TODO: Change the autogenerated stub
    }

    protected function createObject()
    {
        try{
            $conf = Config::getInstance()->getConf('MYSQL');
            $db = new Mysql([
                'host' => $conf['host'],
                'username' => $conf['user'],
                'password' => $conf['password'],
                'db' => $conf['db_name']
            ]);
            if (isset($conf['names'])) {
                $db->rawQuery('SET NAMES ' . $conf['names']);
            }
            return $db;
        }catch (\Throwable $throwable){
            Trigger::throwable($throwable);
            return null;
        }
    }
}